language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-28
    - tools

before_script:
  - chmod +x gradlew

  - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  except:

notifications:
  email: false
